### ISSUE TITLE
Review 1: Lengkapi Readme dan Ketentuan lainnya dari Soal

### ISSUE THREAD

**Issue by priyandari** [dewifajars/UAS_PemrogramanKelompok7#4]
Lengkapi Readme dan Ketentuan lainnya dari Soal, silahkan lihat kembali soal..

**Comment by priyandari** [comment]
b.	Laporan Tugas 
1.	Penjelasan singkat tentang program yang dibuat dan cara kerja program (algoritma) (file pdf).
2.	Program.  File-file program yang dibuat oleh kelompok.
3.	Lampiran. File-file program yang menjadi sumber inspirasi. 
Apabila diperoleh dari buku atau sumber lain, dipersilahkan mengetik ulang sumber-program tersebut dan dibagian atas file-file berikan komentar sumber asal program.

**Comment by dewifajars** [comment]
sudah kami lengkapi berupa penjelasan singkat program dan referensi dalam bentuk pdf serta program pendaftaran pasien. Terima kasih, Pak.
