### ISSUE TITLE
Review 1: Gunakan variabel

### ISSUE THREAD

**Issue by priyandari** [dewifajars/UAS_PemrogramanKelompok7#5]
#standart harga obat= RP10000, standar biaya jasa= RP30000
#standar harga tindakan khusus
   #a. pemberian suntikan = RP20000
   #b. medikasi=RP15000
   #c. penjahitan luka=RP25000
   #d. medikasi kesehatan gigi dan mulut = RP30000

Pelajarilah dan gunakan parameter atau konstanta jika jasa2 itu fixed. Agar rumus layanan menjadi ideal sebagai sebuah program.

**Comment by adam04a** [comment]
ya pak, kami telah menambahkan variabel pada harga harga yang ada sesuai dengan saran bapak. Terimakasih pak yusuf
