### ISSUE TITLE
Review 1: Perjelas inputan dari pengguna

### ISSUE THREAD

**Issue by priyandari** [dewifajars/UAS_PemrogramanKelompok7#6]
Berilah kejelasan yang diinput kode pilihan taau bagaimana.
Bagaimana jika yng diinput juga salah ?
Sudahkan ditangani dgn error handling ?

**Comment by adam04a** [comment]
Terimakasih pak, kami telah menambahkan inturuksi pilihan jawaban, dan jika ada inputan yang tidak sesuai dengan perintah yang ada (inputan salah) kami juga telah menggunakan _try except_  dan juga _while loop_.

**Comment by priyandari** [comment]
Ok
