### ISSUE TITLE
Review 1: proses pendaftarannya ?

### ISSUE THREAD

**Issue by priyandari** [dewifajars/UAS_PemrogramanKelompok7#7]
Tidak terlihat konten bahwa program melakukan proses pendaftran pasien. Silahkan ditambahkan

**Comment by dewifajars** [comment]
sudah kami tambahkan proses pendataan pasien melalui program, yaitu dengan menyimpan informasi pasien yang diinput selama program berjalan ke dalam file KunjunganPasien.txt yang berisi nomor rekam medis, nama, alamat, golongan, jenis pelayanan, diagnosa, obat, serta biaya yang harus dibayarkan olah pasien setelah mendapatkan pelayanan. Terima kasih

j= open('KunjunganPasien.txt', 'a', newline = '')
line=(waktu,test,pasien[test]['nama'],pasien[test]['alamat'],pasien[test]['golongan'],diagnosa,pilih_layanan,terapiObat, bil)
writer = csv.writer(j)
writer.writerow(line)
j.close()
