### ISSUE TITLE
Error: Input obat

### ISSUE THREAD

**Issue by priyandari** [dewifajars/UAS_PemrogramanKelompok7#8]
![Capture](https://user-images.githubusercontent.com/4914090/84588285-61398e00-ae50-11ea-9970-87082911c63e.PNG)

Pengguna tidak tahu obat apa. Diketik obat HUTA error

**Comment by dewifajars** [comment]
Mohon maaf sebelumnya, Pak. Setelah kami mencoba memasukkan HUTA di bagian obat, program masih berjalan. Dalam program, nomor yang terdeteksi hanya nomor yang sudah terdaftar dalam DataPasien.txt sebab setiap pasien yang berobat di fasilitas kesehatan harus terdaftar dan memiliki rekam medis. Dalam hasil running yang Bapak berikan terdapat NameError sebab nomor yang bapak jadikan test tidak terdaftar dalam DataPasien.txt sehingga saat memasukkan "y" pada pertanyaan "apakah anda pernah berobat didini?"nomor rekam medis yang dimasukkan harus ada dalam DataPasien.txt. Terima kasih
